version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./deploy/dockerfiles/Dockerfile
    environment:
     - MONGOHOST=mongodb
    volumes:
      - ./:/code
    ports:
      - "8000:8000"